services:
  patients-ms:
    build:
      context: ./patients-ms
      dockerfile: Dockerfile
    container_name: patients-ms
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      DATABASE_URL: ${DB_URL}
      DATABASE_USER: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}

  clinical-ms:
    build:
      context: ./clinical-ms
      dockerfile: Dockerfile
    container_name: clinical-ms
    restart: unless-stopped
    ports:
      - '8082:8082'
    environment:
      DATABASE_URL: ${DB_URL}
      DATABASE_USER: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - patients-ms

  backend-bff:
    build:
      context: ./medical-system-bff
      dockerfile: Dockerfile
    container_name: backend-bff
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      SERVICES_PATIENTS_BASE_URL: http://patients-ms:8081/api
      SERVICES_CLINICAL_BASE_URL: http://clinical-ms:8082/api
      JWT_ISSUER_URI: ${JWT_ISSUER_URI}
      JWT_JWK_SET_URI: ${JWT_JWK_SET_URI}
    depends_on:
      - patients-ms
      - clinical-ms

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: medical_user
      RABBITMQ_DEFAULT_PASS: medical_pass
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq

  vital-signs-producer-ms:
    build:
      context: ./vital-signs-producer-ms
      dockerfile: Dockerfile
    container_name: vital-signs-producer-ms
    restart: unless-stopped
    ports:
      - '8091:8091'
    environment:
      RABBITMQ_HOST: rabbitmq
      SERVER_PORT: 8091
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: medical_user
      RABBITMQ_PASSWORD: medical_pass
    depends_on:
      - rabbitmq

  alert-oracle-consumer-ms:
    build:
      context: ./alert-oracle-consumer-ms
      dockerfile: Dockerfile
    container_name: alert-oracle-consumer-ms
    restart: unless-stopped
    ports:
      - '8093:8093'
    environment:
      SERVER_PORT: 8093
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: medical_user
      RABBITMQ_PASSWORD: medical_pass
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - rabbitmq

  alert-file-consumer-ms:
    build:
      context: ./alert-file-consumer-ms
      dockerfile: Dockerfile
    container_name: alert-file-consumer-ms
    restart: unless-stopped
    ports:
      - '8094:8094'
    environment:
      SERVER_PORT: 8094
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: medical_user
      RABBITMQ_PASSWORD: medical_pass
      ALERT_FILES_OUTPUT_DIR: /app/generated-alerts
    volumes:
      - ./generated-alerts:/app/generated-alerts
    depends_on:
      - rabbitmq

  summary-producer-ms:
    build:
      context: ./summary-producer-ms
      dockerfile: Dockerfile
    container_name: summary-producer-ms
    restart: unless-stopped
    ports:
      - '8092:8092'
    environment:
      SERVER_PORT: 8092
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: medical_user
      RABBITMQ_PASSWORD: medical_pass
    depends_on:
      - rabbitmq
volumes:
  rabbitmq-data:
