services:
  patients-ms:
    build:
      context: ./patients-ms
      dockerfile: Dockerfile
    container_name: patients-ms
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  clinical-ms:
    build:
      context: ./clinical-ms
      dockerfile: Dockerfile
    container_name: clinical-ms
    restart: unless-stopped
    ports:
      - '8082:8082'
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - patients-ms

  backend-bff:
    build:
      context: ./medical-system-bff
      dockerfile: Dockerfile
    container_name: backend-bff
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      PATIENTS_SERVICE_URL: http://patients-ms:8081
      CLINICAL_SERVICE_URL: http://clinical-ms:8082
      JWT_ISSUER_URI: ${JWT_ISSUER_URI}
      JWT_JWK_SET_URI: ${JWT_JWK_SET_URI}
    depends_on:
      - patients-ms
      - clinical-ms
