CREATE TABLE patients (
  id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  full_name VARCHAR2(120) NOT NULL,
  clinical_id VARCHAR(50) NOT NULL UNIQUE,
  room VARCHAR2(20) NOT NULL,
  status VARCHAR(20) DEFAULT 'CRITICAL' NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NUL;
);

CREATE TABLE vital_signs (
  id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  patient_id NUMBER NOT NULL,
  heart_rate NUMBER NOT NULL,
  oxygen_saturation NUMBER NOT NULL,
  temperature NUMBER(4,1) NOT NULL,
  systolic_pressure NUMBER NOT NULL,
  diastolic_pressure NUMBER NOT NULL,
  measured_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_vital_signs_patient FOREIGN KEY (patient_id) REFERENCES patients(id)
);

CREATE TABLE alerts (
  id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  patient_id NUMBER NOT NULL,
  alert_type VARCHAR2(50) NOT NULL,
  severity VARCHAR(20) NOT NULL,
  message VARCHAR(255) NOT NULL,
  status VARCHAR(20) DEFAULT 'OPEN' NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_alerts_patient FOREIGN KEY (patient_id) REFERENCES patients(id)
);