spring.application.name=kafka-vital-signs-processor-ms

server.port=8096

spring.kafka.bootstrap-servers=localhost:19092,localhost:29092,localhost:39092

spring.kafka.consumer.group-id=vital-signs-processor-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.dsy2206.kafkavitalsignsprocessor.event.VitalSignsEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=com.dsy2206.kafkavitalsignsprocessor.event

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.properties.spring.json.add.type.headers=false

app.kafka.topics.vital-signs=senales_vitales
app.kafka.topics.alerts=alertas