spring.application.name=kafka-vital-signs-producer-ms

server.port=8095

spring.kafka.bootstrap-servers=localhost:19092,localhost:29092,localhost:39092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.acks=all

spring.kafka.producer.retries=3

spring.kafka.producer.properties.spring.json.add.type.headers=false

app.kafka.topics.vital-signs=senales_vitales

app.vital-signs.generation-interval-ms=1000