spring.application.name=medical-system-bff
server.port=${SERVER_PORT:8080}
services.patients.baseUrl=${SERVICES_PATIENTS_BASE_URL:http://localhost:8081/api}
services.clinical.baseUrl=${SERVICES_CLINICAL_BASE_URL:http://localhost:8082/api}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWK_SET_URI}