spring.application.name=kafka-alert-oracle-consumer-ms
spring.config.import=optional:file:../.env[.properties]

server.port=8097

spring.kafka.bootstrap-servers=localhost:19092,localhost:29092,localhost:39092

spring.kafka.consumer.group-id=alert-oracle-consumer-group
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.dsy2206.kafkaalertoracleconsumer.event.AlertEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=com.dsy2206.kafkaalertoracleconsumer.event

app.kafka.topics.alerts=alertas

spring.datasource.url=${DB_URL:jdbc:oracle:thin:@//localhost:1521/xe}
spring.datasource.username=${DB_USERNAME:ADMIN}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect